import pathlib
import posixpath
import subprocess
from abc import abstractmethod
from pathlib import Path
from typing import cast, List, Tuple

from .model import (
    EnumType,
    BitsetType,
    ArrayType,
    BasicType,
    MapType,
    MessgenType,
    Protocol,
    StructType,
    TypeClass,
    VectorType,
    hash_message,
    hash_type,
)

CODEGEN_FILE_PREFIX = "// Code generated by messgen. DO NOT EDIT."

# Converts snake_case to camelCase (first letter lowercase)
def toDartName(name: str, capitalize_first: bool = True) -> str:
    parts = name.split('_')
    if capitalize_first:
        return "".join([x.capitalize() for x in parts])
    else:
        if len(parts) == 0:
            return name
        return parts[0] + "".join([x.capitalize() for x in parts[1:]])

# Converts CamelCase to snake_case for filenames
def toSnakeCase(name: str) -> str:
    import re
    # Insert underscore before uppercase letters (except at start)
    s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name)
    # Insert underscore before uppercase letters followed by lowercase
    return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower()

# Wraps messgen model
class ResolvedType:
    RESERVED_KEY_WORDS = {
        "abstract", "as", "assert", "async", "await", "break", "case", "catch",
        "class", "const", "continue", "covariant", "default", "deferred", "do",
        "dynamic", "else", "enum", "export", "extends", "extension", "external",
        "factory", "false", "final", "finally", "for", "Function", "get", "hide",
        "if", "implements", "import", "in", "interface", "is", "late", "library",
        "mixin", "new", "null", "of", "on", "operator", "part", "rethrow",
        "return", "set", "show", "static", "super", "switch", "sync", "this",
        "throw", "true", "try", "typedef", "var", "void", "while", "with", "yield",
    }

    def __init__(self, model: MessgenType, package: str):
        parsed = model.type.split("/")

        self._model = model
        self._package : list[str] = package.split('/') if package else []
        self._name = toDartName(parsed[-1], True)

    def name(self) -> str:
        return self._name

    def package_full(self) -> str:
        return "/".join(self._package)

    def package_name(self):
        if self._package:
            package_name = self._package[-1]
            if package_name in ResolvedType.RESERVED_KEY_WORDS:
                package_name = "_" + package_name
            return package_name
        return ""

    def imported(self, caller_pkg = None):
        return caller_pkg != self._package

    def reference(self, caller_pkg = None):
        # Dart doesn't need package prefix in same package
        return self._name

    def is_flat(self) -> bool:
        return False

    @abstractmethod
    def alignment(self):
        raise Exception("alignment is not defined for '%s'" % self._model.type)

    @abstractmethod
    def data_size(self):
        raise Exception("data_size is not defined for '%s'" % self._model.type)

    def type_size(self):
        return self.data_size()

    def model(self):
        return self._model

    @abstractmethod
    def render(self):
        raise Exception("There is no render method for type '%s'" % self._model.type)


class FieldGroup:
    def __init__(self):
        self.size = 0
        self.pad = 0
        self.fields = []
        self.flat = True

    def description(self) -> str:
        return ",".join([name for name, _ in self.fields])

    def add_field(self, name: str, field: ResolvedType):
        self.fields.append((name, field))
        self.flat = self.flat and field.is_flat()

        if self.size == None:
            return
        elif field.data_size() != None:
            self.size += field.data_size()
        else:
            self.size = None


class ResolvedBuiltin(ResolvedType):
    # Map messgen types to Dart types
    TYPE_MAP = {
        "int8": "int",
        "uint8": "int",
        "int16": "int",
        "uint16": "int",
        "int32": "int",
        "uint32": "int",
        "int64": "int",
        "uint64": "int",
        "float32": "double",
        "float64": "double",
        "bool": "bool",
        "string": "String",
        "bytes": "Uint8List",
    }

    def __init__(self, type_def: MessgenType, package: str):
        super().__init__(type_def, package)
        if type_def.type_class == TypeClass.bytes:
            self._name = "Uint8List"
        elif type_def.type in self.TYPE_MAP:
            self._name = self.TYPE_MAP[type_def.type]
        else:
            self._name = type_def.type

    def imported(self, caller_pkg = None):
        _ = caller_pkg
        return False

    def reference(self, caller_pkg=None):
        _ = caller_pkg
        return self._name

    def alignment(self):
        if isinstance(self._model, BasicType):
            if self._model.type_class in [TypeClass.scalar]:
                return self._model.size
            elif self._model.type_class in [TypeClass.string, TypeClass.bytes]:
                return 8
        raise Exception("Unknown builtin type class for '%s'" % self._model.type)

    def is_flat(self):
        return self._model.type_class == TypeClass.scalar

    def data_size(self):
        if isinstance(self._model, BasicType):
            if self._model.type_class in [TypeClass.scalar]:
                return self._model.size
            elif self._model.type_class in [TypeClass.string, TypeClass.bytes]:
                return None
        raise Exception("Unknown builtin type class for '%s'" % self._model.type)

    def type_size(self):
        if isinstance(self._model, BasicType):
            if self._model.type_class in [TypeClass.scalar]:
                return self._model.size
            elif self._model.type_class in [TypeClass.string, TypeClass.bytes]:
                return None
        raise Exception("Unknown builtin type class for '%s'" % self._model.type)

    def render(self):
        raise Exception("Render is not supported for ResolvedBuiltin")


class ResolvedSlice(ResolvedType):
    def __init__(self, model: ArrayType | VectorType, elem_type : ResolvedType, package: str):
        super().__init__(model, package)
        self._element = elem_type

    def imported(self, caller_pkg = None):
        return self._element.imported(caller_pkg)

    def reference(self, caller_pkg = None):
        return "List<%s>" % self._element.reference(caller_pkg)

    def alignment(self):
        if isinstance(self._model, ArrayType):
            return self._element.alignment()
        return 8

    def is_flat(self) -> bool:
        return False

    def type_size(self):
        if isinstance(self._model, ArrayType) and self._element.type_size():
            return self._model.array_size * self._element.type_size()
        return None

    def data_size(self):
        if isinstance(self._model, ArrayType) and self._element.data_size() != None:
            return self._element.data_size() * self._model.array_size
        return None

    def render(self):
        raise Exception("Render is not supported for ResolvedSlice")


class ResolvedMap(ResolvedType):
    def __init__(self, type_def: MapType, key: ResolvedType, value: ResolvedType, package : str):
        super().__init__(type_def, package)
        self._key = key 
        self._value = value 

    def imported(self, caller_pkg = None):
        return self._key.imported(caller_pkg) or self._value.imported(caller_pkg)

    def reference(self, caller_pkg = None):
        return "Map<%s, %s>" % (self._key.reference(caller_pkg), self._value.reference(caller_pkg))

    def is_flat(self) -> bool:
        return False

    def alignment(self):
        return 8

    def type_size(self):
        return None

    def data_size(self):
        return None

    def render(self):
        raise Exception("Render is not supported for ResolvedMap")


class ResolvedEnum(ResolvedType):
    def __init__(self, type_def: EnumType, base: ResolvedType, package: str):
        super().__init__(type_def, package)
        self._base = base

    def model(self):
        return cast(EnumType, self._model)
    
    def reference(self, caller_pkg = None):
        # Enums are represented as their enum class type in field declarations
        return self._name

    def alignment(self):
        return self._base.alignment()

    def data_size(self):
        return self._base.data_size()

    def type_size(self):
        return self._base.type_size()

    def is_flat(self):
        return True

    def render(self):
        model = self.model()
        
        yield f"{CODEGEN_FILE_PREFIX}\n"
        yield f"import 'dart:typed_data';\n"
        yield f"import 'package:messgen/messgen.dart';\n"
        
        if model.comment:
            yield f"/// {model.comment}"
        
        yield f"class {self._name} {{"
        yield f"  final int value;"
        yield ""
        yield f"  const {self._name}(this.value);"
        yield ""
        
        # Constants for enum values (now as instances of the enum class)
        for val in model.values:
            if val.comment:
                yield f"  /// {val.comment}"
            val_name = toDartName(val.name, False)
            yield f"  static const {self._name} {val_name} = {self._name}({val.value});"
        
        yield ""
        
        yield f"  @override"
        yield f"  bool operator ==(Object other) =>"
        yield f"      identical(this, other) ||"
        yield f"          other is {self._name} &&"
        yield f"              runtimeType == other.runtimeType &&"
        yield f"              value == other.value;"
        yield ""
        yield f"  @override"
        yield f"  int get hashCode => value.hashCode;"
        yield ""

        yield f"  {self._name} copyWith({{int? value}}) {{"
        yield f"    return {self._name}(value ?? this.value);"
        yield f"  }}"
        yield ""
        yield f"  {self._name} copy() => copyWith();"
        yield ""

        # 3. Generate Static List of all values
        all_const_names = [toDartName(val.name, False) for val in model.values]
        yield f"  static List<{self._name}> values = [{', '.join(all_const_names)}];"
        yield ""

        # 4. Generate toString() override
        yield f"  @override"
        yield f"  String toString() {{"
        yield f"    switch (value) {{"
        for val in model.values:
            val_name = toDartName(val.name, False)
            yield f"      case {val.value}: return '{val.name}';"
        yield f"      default: return 'unknown($value)';"
        yield f"    }}"
        yield f"  }}"
        yield f"}}"


class ResolvedBitset(ResolvedType):
    def __init__(self, type_def: BitsetType, base: ResolvedType, package: str):
        super().__init__(type_def, package)
        self._base = base

    def model(self):
        return cast(BitsetType, self._model)

    def reference(self, caller_pkg = None):
        # Bitsets are represented as their bitset class type in field declarations
        return self._name

    def alignment(self):
        return self._base.alignment()

    def data_size(self):
        return self._base.data_size()

    def type_size(self):
        return self._base.type_size()

    def is_flat(self):
        return True

    def render(self):
        model = self.model()

        yield f"{CODEGEN_FILE_PREFIX}\n"
        yield f"import 'dart:typed_data';\n"
        yield f"import 'package:messgen/messgen.dart';\n"

        if model.comment:
            yield f"/// {model.comment}"

        yield f"class {self._name} {{"
        yield f"  late int value;"
        yield ""
        yield f"  {self._name}(this.value);"
        yield ""

        # Bit constants
        for bit in model.bits:
            if bit.comment:
                yield f"  /// {bit.comment}"
            bit_name = toDartName(bit.name, False)
            yield f"  static const int {bit_name} = {bit.offset};"

        yield ""

        # has method
        yield f"  bool has(int bit) {{"
        yield f"    return (value & (1 << bit)) != 0;"
        yield f"  }}"
        yield ""

        # set method - fluent mutable
        yield f"  {self._name} set(int bit) {{"
        yield f"    value |= (1 << bit);"
        yield f"    return this;"
        yield f"  }}"
        yield ""

        # clear method - fluent mutable
        yield f"  {self._name} clear(int bit) {{"
        yield f"    value &= ~(1 << bit);"
        yield f"    return this;"
        yield f"  }}"
        yield ""

        yield f"  {self._name} copyWith({{int? value}}) {{"
        yield f"    return {self._name}(value ?? this.value);"
        yield f"  }}"
        yield ""
        yield f"  {self._name} copy() => copyWith();"
        yield ""

        # toString method
        yield f"  @override"
        yield f"  String toString() {{"
        yield f"    final bits = <String>[];"
        for bit in model.bits:
            bit_name = toDartName(bit.name, False)
            yield f"    if (has({bit_name})) bits.add('{bit.name}');"
        yield f"    return bits.isEmpty ? '{{}}' : '{{${{bits.join(' | ')}}}}';"
        yield f"  }}"
        yield f"}}"


class ResolvedStruct(ResolvedType):
    def __init__(self, type_def: StructType, hash: int | None, package: str):
        super().__init__(type_def, package)
        self._hash = hash
        self._fields: list[tuple[str, ResolvedType]] = []
        self._field_defs: dict[str, str | None] = {}  # Store field comments

    def model(self):
        return cast(StructType, self._model)

    def add_field(self, name: str, field: ResolvedType, comment: str | None = None):
        self._fields.append((name, field))
        self._field_defs[name] = comment

    def fields(self):
        return self._fields

    def alignment(self):
        return 8

    def data_size(self):
        total = 0
        for _, field in self._fields:
            size = field.data_size()
            if size is None:
                return None
            total += size
        return total if total > 0 else 0

    def is_flat(self) -> bool:
        for _, field in self._fields:
            if not field.is_flat():
                return False
        return True

    def renderSize(self, name:str, cur: ResolvedType, step = 0):
        if cur._model.type_class == TypeClass.string:
            yield f"    result += 4 + utf8.encode({name}).length;"
        elif cur._model.type_class == TypeClass.bytes:
            yield f"    result += 4 + {name}.length;"
        elif cur._model.type_class == TypeClass.struct:
            yield f"    result += {name}.serializedSize();"
        elif isinstance(cur, ResolvedEnum):
            # Enums use their base type size
            yield from self.renderSize(name, cur._base, step)
        elif isinstance(cur, ResolvedBitset):
            # Bitsets use their base type size
            yield from self.renderSize(name, cur._base, step)
        elif isinstance(cur, ResolvedBuiltin):
            yield f"    result += {cur.type_size()};"
        elif isinstance(cur, ResolvedSlice):
            elem_idx = f"i{step}"
            elem_name = f"elem{step}"
            if cur._model.type_class != TypeClass.array:
                yield f"    result += 4;"
            if cur._element.data_size() != None and cur._element.is_flat():
                yield f"    result += {name}.length * {cur._element.type_size()};"
            else:
                yield f"    for (final {elem_name} in {name}) {{"
                yield from self.renderSize(elem_name, cur._element, step+1)
                yield f"    }}"
        elif isinstance(cur, ResolvedMap):
            yield f"    result += 4;"
            yield f"    {name}.forEach((key, value) {{"
            yield f"      // Count key"
            yield from self.renderSize("key", cur._key, step+1)
            yield f"      // Count value"
            yield from self.renderSize("value", cur._value, step+1)
            yield f"    }});"

    def renderSerialize(self, name: str, cur: ResolvedType, step = 0):
        if cur._model.type_class == TypeClass.string:
            yield f"    writer.writeString({name});"
        elif cur._model.type_class == TypeClass.bytes:
            yield f"    writer.writeBytes({name});"
        elif cur._model.type_class == TypeClass.struct:
            yield f"    final bytesWritten = {name}.serialize(Uint8List.sublistView(output, writer.offset));"
            yield f"    writer.advance(bytesWritten);"
        elif isinstance(cur, ResolvedEnum):
            # Enums are serialized by accessing their .value field
            yield from self.renderSerialize(f"{name}.value", cur._base, step)
        elif isinstance(cur, ResolvedBitset):
            # Bitsets are serialized by accessing their .value field
            yield from self.renderSerialize(f"{name}.value", cur._base, step)
        elif isinstance(cur, ResolvedBuiltin):
            type_name = cur._model.type
            if type_name == "int8":
                yield f"    writer.writeInt8({name});"
            elif type_name == "uint8":
                yield f"    writer.writeUint8({name});"
            elif type_name == "int16":
                yield f"    writer.writeInt16({name});"
            elif type_name == "uint16":
                yield f"    writer.writeUint16({name});"
            elif type_name == "int32":
                yield f"    writer.writeInt32({name});"
            elif type_name == "uint32":
                yield f"    writer.writeUint32({name});"
            elif type_name == "int64":
                yield f"    writer.writeInt64({name});"
            elif type_name == "uint64":
                yield f"    writer.writeUint64({name});"
            elif type_name == "float32":
                yield f"    writer.writeFloat32({name});"
            elif type_name == "float64":
                yield f"    writer.writeFloat64({name});"
            elif type_name == "bool":
                yield f"    writer.writeBool({name});"
        elif isinstance(cur, ResolvedSlice):
            elem_name = f"elem{step}"
            if cur._model.type_class != TypeClass.array:
                yield f"    writer.writeUint32({name}.length);"

            if cur._element.data_size() != None and cur._element.is_flat():
                # For flat types, we can serialize efficiently
                yield f"    for (final {elem_name} in {name}) {{"
                yield from self.renderSerialize(elem_name, cur._element, step+1)
                yield f"    }}"
            else:
                yield f"    for (final {elem_name} in {name}) {{"
                yield from self.renderSerialize(elem_name, cur._element, step+1)
                yield f"    }}"
        elif isinstance(cur, ResolvedMap):
            yield f"    writer.writeUint32({name}.length);"
            yield f"    {name}.forEach((key, value) {{"
            yield f"      // Write key"
            yield from self.renderSerialize("key", cur._key, step+1)
            yield f"      // Write value"
            yield from self.renderSerialize("value", cur._value, step+1)
            yield f"    }});"

    def renderDeserialize(self, name: str, cur: ResolvedType, step = 0):
        # --- Nested Structs (Return Record) ---
        if cur._model.type_class == TypeClass.struct:
            res_var = f"res{step}"
            yield f"    final ({cur.reference()} {name}, int {res_var}) ="
            yield f"        {cur.reference()}.deserialize(Uint8List.sublistView(input, reader.offset));"
            yield f"    reader.advance({res_var});"

        # --- Strings & Bytes ---
        elif cur._model.type_class == TypeClass.string:
            yield f"    final {name} = reader.readString();"
        elif cur._model.type_class == TypeClass.bytes:
            yield f"    final {name} = reader.readBytes();"

        # --- Enums / Bitsets ---
        elif isinstance(cur, (ResolvedEnum, ResolvedBitset)):
            temp_var = f"temp{step}"
            yield from self.renderDeserialize(temp_var, cur._base, step)
            yield f"    final {name} = {cur.reference()}({temp_var});"

        # --- Builtin Scalars ---
        elif isinstance(cur, ResolvedBuiltin):
            type_name = cur._model.type
            # reader methods are usually readUint32, readFloat64, etc.
            yield f"    final {name} = reader.read{type_name.capitalize()}();"

        # --- Slices (Lists/Vectors) ---
        elif isinstance(cur, ResolvedSlice):
            yield f"    final {name} = <{cur._element.reference()}>[];"

            if isinstance(cur._model, ArrayType):
                count_expr = str(cur._model.array_size)
            else:
                yield f"    final count{step} = reader.readUint32();"
                count_expr = f"count{step}"

            yield f"    for (var i{step} = 0; i{step} < {count_expr}; i{step}++) {{"
            elem_name = f"elem{step}"
            yield from self.renderDeserialize(elem_name, cur._element, step + 1)
            yield f"      {name}.add({elem_name});"
            yield f"    }}"

        # --- Maps ---
        elif isinstance(cur, ResolvedMap):
            yield f"    final {name} = <{cur._key.reference()}, {cur._value.reference()}>{{}};"
            yield f"    final mapCount{step} = reader.readUint32();"
            yield f"    for (var i{step} = 0; i{step} < mapCount{step}; i{step}++) {{"
            key_name = f"key{step}"
            val_name = f"val{step}"
            yield from self.renderDeserialize(key_name, cur._key, step + 1)
            yield from self.renderDeserialize(val_name, cur._value, step + 2)
            yield f"      {name}[{key_name}] = {val_name};"
            yield f"    }}"

    def _generateDeepCopyExpr(self, expr: str, field_type: ResolvedType) -> str:
        """Recursively generates the Dart expression to deep copy a type."""

        # 1. Handle Lists (Arrays/Vectors)
        if isinstance(field_type, ResolvedSlice):
            # We need to map the inner elements
            inner_copy = self._generateDeepCopyExpr("e", field_type._element)
            return f"{expr}.map((e) => {inner_copy}).toList()"

        # 2. Handle Maps
        elif isinstance(field_type, ResolvedMap):
            # Maps need to copy both keys (usually primitives) and values
            key_copy = self._generateDeepCopyExpr("k", field_type._key)
            val_copy = self._generateDeepCopyExpr("v", field_type._value)
            return f"{expr}.map((k, v) => MapEntry({key_copy}, {val_copy}))"

        # 3. Handle Structs, Enums, and Bitsets (Anything with a .copy() method)
        elif field_type._model.type_class in [TypeClass.struct, TypeClass.enum, TypeClass.bitset]:
            return f"{expr}.copy()"

        # 4. Handle Primitives (int, double, bool, String, Uint8List)
        # Uint8List is handled via sublist for a true memory copy
        if field_type.reference() == "Uint8List":
            return f"{expr}.sublist(0)"

        # Absolute primitives are passed by value
        return expr

    def renderCopyWith(self):
        yield "  /// Creates a deep copy of this class with the given fields replaced."
        yield f"  {self._name} copyWith("

        if self._fields:
            yield f" {{"

        for field_name, field in self._fields:
            dart_field_name = toDartName(field_name, False)
            yield f"    {field.reference(self._package)}? {dart_field_name},"

        if self._fields:
            yield f"}}"

        yield "  ) {"
        yield f"    return {self._name}("

        for field_name, field in self._fields:
            dname = toDartName(field_name, False)

            # Generate the recursive copy logic for the existing 'this' value
            this_copy = self._generateDeepCopyExpr(f"this.{dname}", field)

            # Generate the recursive copy logic for the provided parameter
            param_copy = self._generateDeepCopyExpr(dname, field)

            # Final Dart line logic:
            # If param is provided, deep copy it.
            # Otherwise, deep copy the current field to maintain isolation.
            yield f"      {dname}: {dname} != null ? {param_copy} : {this_copy},"

        yield "    );"
        yield "  }"

    def render(self):
        model = self.model()

        yield f"{CODEGEN_FILE_PREFIX}"
        yield f"import 'dart:typed_data';"
        yield f"import 'dart:convert';"
        yield f"import 'package:messgen/messgen.dart';"

        # Helper function to collect all types that need imports
        def collect_import_types(resolved_type, imports_set):
            """Recursively collect all struct/enum/bitset types that need imports"""
            if resolved_type._model.type_class in [TypeClass.enum, TypeClass.bitset]:
                # Always import enums and bitsets
                pkg_tuple = tuple(resolved_type._package) if resolved_type._package else ()
                imports_set.add((pkg_tuple, resolved_type._name))
            elif resolved_type._model.type_class == TypeClass.struct:
                # Import structs (even in same package for consistency)
                pkg_tuple = tuple(resolved_type._package) if resolved_type._package else ()
                imports_set.add((pkg_tuple, resolved_type._name))
            elif isinstance(resolved_type, ResolvedSlice):
                # Recursively check element type for arrays/vectors
                collect_import_types(resolved_type._element, imports_set)
            elif isinstance(resolved_type, ResolvedMap):
                # Recursively check key and value types for maps
                collect_import_types(resolved_type._key, imports_set)
                collect_import_types(resolved_type._value, imports_set)

        # Import dependencies
        imported_packages = set()
        for _, field in self._fields:
            collect_import_types(field, imported_packages)

        for pkg_tuple, type_name in sorted(imported_packages):
            # Convert type name to snake_case for filename
            filename = toSnakeCase(type_name) + "_gen.dart"

            # Calculate relative path from this file's package to the imported type's package
            if pkg_tuple and pkg_tuple != tuple(self._package):
                # Different package - calculate relative import path
                # self._package and pkg_tuple are tuples of path components
                # Convert to strings for path calculation
                from_path = "/".join(self._package) if self._package else ""
                to_path = "/".join(pkg_tuple) if pkg_tuple else ""

                # Use posixpath to calculate relative path
                if from_path and to_path:
                    rel_path = posixpath.relpath(to_path, start=from_path)
                    yield f"import '{rel_path}/{filename}';\n"
                else:
                    # Fallback to just the filename
                    yield f"import '{filename}';\n"
            else:
                # Same package - import by filename only
                yield f"import '{filename}';\n"

        if model.comment:
            yield f"/// {model.comment}"

        yield f"class {self._name} implements Serializable {{"

        # Fields (no default values since we use required constructor parameters)
        for field_name, field in self._fields:
            dart_field_name = toDartName(field_name, False)
            field_type = field.reference(self._package)
            field_comment = self._field_defs.get(field_name)
            if field_comment:
                yield f"  /// {field_comment}"
            yield f"  {field_type} {dart_field_name};"

        yield ""

        # 2. Constructor
        if self._fields:
            yield f"  {self._name}({{"
            for field_name, _ in self._fields:
                dart_field_name = toDartName(field_name, False)
                yield f"    required this.{dart_field_name},"
            yield f"  }});"
        else:
            yield f"  {self._name}();"

        yield ""

        # 3. Empty Factory (Returns a default immutable instance)
        yield f"  factory {self._name}.empty() {{"
        if self._fields:
            yield f"    return {self._name}("
            for field_name, field in self._fields:
                dart_name = toDartName(field_name, False)
                # Use a helper to get the correct 'zero' value for the type
                yield f"      {dart_name}: {self._getDefaultValue(field)},"
            yield "    );"
        else:
            yield f"    return {self._name}();"
        yield "  }"
        yield ""

        # 4. CopyWith support
        yield from self.renderCopyWith()
        yield ""

        yield f"  {self._name} copy() => copyWith();"
        yield ""

        # 5. Static deserialize factory
        yield f"  static ({self._name}, int) deserialize(Uint8List input) {{"
        yield f"    final reader = BufferReader(input);"

        # Iterate and generate local variable assignments
        for i, (field_name, field) in enumerate(self._fields):
            dart_name = toDartName(field_name, False)
            yield from self.renderDeserialize(dart_name, field, i * 100)

        yield "    return ("
        yield f"      {self._name}("
        for field_name, _ in self._fields:
            dart_name = toDartName(field_name, False)
            yield f"        {dart_name}: {dart_name},"
        yield "      ),"
        yield "      reader.offset"
        yield "    );"
        yield "  }"
        yield ""

        # 6. SerializedSize method
        yield f"  int serializedSize() {{"
        yield f"    int result = 0;"
        for field_name, field in self._fields:
            dart_field_name = toDartName(field_name, False)
            yield from self.renderSize(dart_field_name, field)
        yield f"    return result;"
        yield f"  }}"
        yield ""

        # 7. Serialize method
        yield f"  int serialize(Uint8List output) {{"
        yield f"    final writer = BufferWriter(output);"
        for field_name, field in self._fields:
            dart_field_name = toDartName(field_name, False)
            yield from self.renderSerialize(dart_field_name, field)
        yield f"    return writer.offset;"
        yield f"  }}"
        yield ""

        # 8. Hash method
        yield f"  BigInt hash() {{"
        if self._hash is not None:
            yield f"    return BigInt.parse('{self._hash}');"
        else:
            yield f"    return BigInt.zero;"
        yield f"  }}"

        yield f"  @override"
        yield f"  String toString() {{"
        yield f"    return '{self._name}(" + ", ".join(
            [f"{field_name}: ${{{toDartName(field_name, False)}}}" for field_name, _ in self._fields]
        ) + ")';"
        yield f"  }}"

        yield f"}}"

    def _getDefaultValue(self, field: ResolvedType) -> str:
        """Returns the Dart literal for a default 'empty' value."""
        # 1. Check for Enums/Bitsets (They are classes wrapping an int)
        if isinstance(field, (ResolvedEnum, ResolvedBitset)):
            return f"{field.reference()}(0)"

        # 2. Check for Nested Structs
        if field._model.type_class == TypeClass.struct:
            return f"{field.reference()}.empty()"

        # 3. Check for Collections (Slices/Vectors/Arrays)
        if isinstance(field, ResolvedSlice):
            if isinstance(field._model, ArrayType):
                n = field._model.array_size
                if n == 0:
                    return "[]"
                default_elem = self._getDefaultValue(field._element)
                return f"List.generate({n}, (_) => {default_elem})"
            return "[]" # Vector

        if isinstance(field, ResolvedMap):
            return "{}"

        # 4. Builtins
        if isinstance(field, ResolvedBuiltin):
            t = field._model.type
            if t == "bool": return "false"
            if t == "string": return "''"
            if t == "bytes": return "Uint8List(0)"
            # All numeric scalars (int8, uint32, float64, etc.)
            return "0"

        return "null" # Fallback (should be avoided for final fields)


def render_protocol(proto_name: str, proto_class_name: str, proto_full_path: str, proto: Protocol,
                   resolved: dict[str, ResolvedType], types: dict[str, MessgenType]):
    """Generate protocol dispatcher code"""

    # Compute protocol hash
    proto_hash = 0
    message_hashes = {}
    for msg_id, msg in proto.messages.items():
        type_hash = hash_type(types[msg.type], types)
        msg_hash = hash_message(msg) ^ type_hash if type_hash else 0
        proto_hash ^= msg_hash
        # Store message hash as-is for BigInt
        message_hashes[msg_id] = msg_hash

    yield f"{CODEGEN_FILE_PREFIX}\n"
    yield f"import 'dart:typed_data';\n"
    yield f"import 'package:messgen/messgen.dart';\n"

    # Import message types with proper relative paths
    # Group imports by their type folder
    type_imports: dict[str, set[str]] = {}  # Maps type folder to set of filenames
    msg_type_names = {}  # Map message IDs to type class names

    for msg_id, msg in proto.messages.items():
        if msg.type in types:
            msg_type = types[msg.type]
            if msg_type.type_class == TypeClass.struct:
                if msg.type in resolved:
                    resolved_type = resolved[msg.type]
                    msg_type_names[msg_id] = resolved_type.name()

                    # Extract the type folder from the full type path
                    # e.g., "mynamespace/types/subspace/complex_struct" -> "mynamespace/types/subspace"
                    #       "mynamespace/types/simple_struct" -> "mynamespace/types"
                    type_path_parts = msg.type.split("/")
                    if len(type_path_parts) > 2:
                        # Has namespace/types or namespace/types/subspace
                        type_folder = "/".join(type_path_parts[:-1])
                    else:
                        type_folder = msg.type.rsplit("/", 1)[0]

                    # Calculate relative path from protocol directory to type directory
                    rel_path = posixpath.relpath(type_folder, start=proto_full_path)

                    # Use the actual generated filename with snake_case
                    filename = toSnakeCase(resolved_type.name()) + "_gen.dart"

                    if rel_path not in type_imports:
                        type_imports[rel_path] = set()
                    type_imports[rel_path].add(filename)

    # Generate import statements
    for rel_path in sorted(type_imports.keys()):
        for filename in sorted(type_imports[rel_path]):
            yield f"import '{rel_path}/{filename}';\n"

    yield ""

    # Message handler type - must be outside class
    yield f"typedef MessageHandler = Future<void> Function(dynamic context, Uint8List body);"
    yield ""

    yield f"class {proto_class_name}Protocol {{"
    yield f"  static const int id = {proto.proto_id};"
    yield f"  static const String name = '{proto.name}';"
    yield f"  static final BigInt hash = BigInt.parse('{proto_hash}');"
    yield ""

    # Message IDs and hashes
    for msg_id, msg in proto.messages.items():
        msg_name = toDartName(msg.name, False)
        yield f"  static const int {msg_name}Id = {msg_id};"
        yield f"  static final BigInt {msg_name}Hash = BigInt.parse('{message_hashes[msg_id]}');"

    yield ""

    # Message ID to constructor map
    yield f"  static final Map<int, (Serializable, int) Function(Uint8List)> messageIdToConstructor = {{"
    for msg_id, msg in proto.messages.items():
        if msg_id in msg_type_names:
            type_name = msg_type_names[msg_id]
            yield f"    {msg_id}: (input) => {type_name}.deserialize(input),"
    yield f"  }};"
    yield ""
    
    # Handlers map
    yield f"  final Map<int, MessageHandler> _handlers = {{}};"
    yield ""
    
    # Set handler methods
    for msg_id, msg in proto.messages.items():
        msg_name = toDartName(msg.name, True)
        camel_msg_name = toDartName(msg.name, False)
        yield f"  void setHandler{msg_name}(MessageHandler handler) {{"
        yield f"    _handlers[{camel_msg_name}Id] = handler;"
        yield f"  }}"
        yield ""
    
    # Dispatch method
    yield f"  Future<void> dispatch(dynamic context, int messageId, Uint8List body) async {{"
    yield f"    final handler = _handlers[messageId];"
    yield f"    if (handler == null) {{"
    yield f"      throw MessgenException('No handler found for message id $messageId');"
    yield f"    }}"
    yield f"    await handler(context, body);"
    yield f"  }}"
    yield ""
    
    # Get message name
    yield f"  static String messageName(int messageId) {{"
    yield f"    switch (messageId) {{"
    for msg_id, msg in proto.messages.items():
        yield f"      case {msg_id}: return '{msg.name}';"
    yield f"      default: return 'unknown';"
    yield f"    }}"
    yield f"  }}"
    yield f"}}"


class DartGenerator:
    PROTO_TYPE_VAR_TYPE = "int"

    def __init__(self, options: dict):
        self._options: dict = options
        self._types: dict[str, MessgenType] = {}
        self._resolved: dict[str, ResolvedType] = {}
        self._out_dir: Path | None = None
        self._protocols: dict[str, Protocol] = {}

    def generate_type(self, out_dir: Path, typename: str, ident=0) -> ResolvedType:
        if typename in self._resolved:
            return self._resolved[typename]
        elif typename not in self._types:
            raise Exception("Unknown type: %s" % (typename))

        resolved : ResolvedType | None = None
        type_def = self._types[typename]

        # Determine package for non-builtin types
        if type_def.type_class not in [TypeClass.scalar, TypeClass.bytes, TypeClass.string]:
            package = f"{out_dir.name}/{type_def.type}"
            package = package.rsplit("/", 1)[0]
        else:
            package = ""

        if type_def.type_class == TypeClass.array or type_def.type_class == TypeClass.vector:
            slice_type = cast(ArrayType | VectorType, type_def)
            tmp = self.generate_type(out_dir, slice_type.element_type, ident+2)
            resolved = ResolvedSlice(slice_type, tmp, package)
        elif type_def.type_class == TypeClass.map:
            map_type = cast(MapType, type_def)
            key_t = self.generate_type(out_dir, map_type.key_type, ident+2)
            val_t = self.generate_type(out_dir, map_type.value_type, ident+2)
            resolved = ResolvedMap(map_type, key_t, val_t, package)
        elif type_def.type_class == TypeClass.enum:
            enum_type = cast(EnumType, type_def)
            base = self.generate_type(out_dir, enum_type.base_type, ident+2)
            resolved = ResolvedEnum(enum_type, base, package)
        elif type_def.type_class == TypeClass.bitset:
            bitset_type = cast(BitsetType, type_def)
            base = self.generate_type(out_dir, bitset_type.base_type, ident+2)
            resolved = ResolvedBitset(bitset_type, base, package)
        elif type_def.type_class == TypeClass.struct:
            struct_hash: int | None = hash_type(type_def, self._types)

            struct_type = cast(StructType, type_def)
            resolved_struct = ResolvedStruct(struct_type, struct_hash, package)

            for field in struct_type.fields:
                fresolved = self.generate_type(out_dir, field.type, ident+2)
                resolved_struct.add_field(field.name, fresolved, field.comment)

            resolved = resolved_struct
        elif isinstance(type_def, BasicType):
            resolved = ResolvedBuiltin(type_def, package)
        else:
            raise Exception("Type %s is not struct/enum/bitset: %s" % (typename, type_def))

        self._resolved[typename] = resolved
        return resolved

    def generate_types(self, out_dir: Path, types: dict[str, MessgenType]) -> None:
        self._types = types
        self._out_dir = out_dir

        for type_name, _ in types.items():
            type_obj = self.generate_type(out_dir, type_name)

            # Only struct/enum/bitset gets generated
            output = None
            if type_obj._model.type_class in [TypeClass.struct, TypeClass.enum, TypeClass.bitset]:
                # Get relative path from type
                pkg = "/".join(type_obj._package).removeprefix(f"{out_dir.name}/")
                pkg = pkg.removeprefix("/")
                output = out_dir / pathlib.Path(pkg)
                # Convert type name to snake_case for filename
                filename = toSnakeCase(type_obj._name) + "_gen.dart"
                output = output.joinpath(filename)
            else:
                continue

            output.parent.mkdir(parents=True, exist_ok=True)
            with open(output, 'w') as file:
                for line in type_obj.render():
                    print(line, file=file)
        # Generate barrel files for types after all types are generated
        self._generate_type_barrel_files(out_dir, types)

    def generate_protocols(self, out_dir: Path, types: dict[str, MessgenType], protocols: dict[str, Protocol]) -> None:
        self.generate_types(out_dir, types)

        self._protocols = protocols
        self._out_dir = out_dir
        
        for proto_full_name, proto_def in protocols.items():
            proto_name = proto_full_name.split("/")[-1]

            if proto_name in ResolvedType.RESERVED_KEY_WORDS:
                proto_name = "_" + proto_name

            proto_class_name = toDartName(proto_name, True)
            file_name = out_dir / proto_full_name / "proto_gen.dart"

            file_name.parent.mkdir(parents=True, exist_ok=True)

            with open(file_name, 'w') as file:
                for line in render_protocol(proto_name, proto_class_name, proto_full_name, proto_def, self._resolved, self._types):
                    print(line, file=file)
                file.close()

            # Format the generated Dart code
            try:
                subprocess.call(["dart", "format", file_name], text=True)
            except:
                pass  # dart format might not be available
        
        # Generate barrel files for protocols after all protocols are generated
        self._generate_protocol_barrel_files(out_dir, protocols)
    
    def _generate_type_barrel_files(self, out_dir: Path, types: dict[str, MessgenType]) -> None:
        """Generate barrel files (export files) for type folders"""
        from collections import defaultdict
        
        # Group types by folder
        types_by_folder = defaultdict(list)
        for typename, type_def in types.items():
            if type_def.type_class in [TypeClass.struct, TypeClass.enum, TypeClass.bitset]:
                if typename in self._resolved:
                    resolved_type = self._resolved[typename]
                    # Extract folder path
                    type_path_parts = typename.split("/")
                    if len(type_path_parts) > 2:
                        folder = "/".join(type_path_parts[:-1])
                    else:
                        folder = typename.rsplit("/", 1)[0]
                    
                    filename = toSnakeCase(resolved_type.name()) + "_gen.dart"
                    types_by_folder[folder].append(filename)
        
        # Generate barrel file for each types folder
        for folder, filenames in types_by_folder.items():
            barrel_path = out_dir / folder / "index.dart"
            barrel_path.parent.mkdir(parents=True, exist_ok=True)
            
            with open(barrel_path, 'w') as f:
                f.write(f"{CODEGEN_FILE_PREFIX}\n\n")
                f.write("// Barrel file - exports all types in this folder\n\n")
                for filename in sorted(filenames):
                    f.write(f"export '{filename}';\n")
            
            # Format the barrel file
            try:
                subprocess.call(["dart", "format", barrel_path], text=True)
            except:
                pass
    
    def _generate_protocol_barrel_files(self, out_dir: Path, protocols: dict[str, Protocol]) -> None:
        """Generate barrel files (export files) for protocol folders"""
        # Generate barrel files for protocols
        for proto_full_name in protocols.keys():
            proto_dir = out_dir / proto_full_name
            barrel_path = proto_dir / "index.dart"
            
            with open(barrel_path, 'w') as f:
                f.write(f"{CODEGEN_FILE_PREFIX}\n\n")
                f.write("// Barrel file - exports protocol\n\n")
                f.write("export 'proto_gen.dart';\n")
            
            # Format the barrel file
            try:
                subprocess.call(["dart", "format", barrel_path], text=True)
            except:
                pass
