name: Go CI

on:
  push:
    branches: ["master", "v1"]
  pull_request:
    branches: ["master", "v1"]

jobs:
  build:
    name: Test and Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Go dependencies
        run: go mod download

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Go Codegen And Run Go Tests
        run: make test-golang

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1
          args: run -v --config golangci.yaml ./build-golang-test/... ./port/golang/... ./tests/golang/...
